CREATE DATABASE __DB_DATABASE_NAME__;
CREATE USER '__DB_USERNAME__'@'localhost' IDENTIFIED BY '__DB_PASSWORD__';
GRANT SELECT, INSERT, UPDATE, DELETE, CREATE, DROP, ALTER, CREATE TEMPORARY TABLES, LOCK TABLES ON __DB_DATABASE_NAME__.* TO '__DB_USERNAME__'@'localhost';